server:
  port: 8086


spring:
  datasource:
    url: jdbc:mysql://172.68.0.176:3306/future_auth_data?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: future123456
    driver-class-name: com.mysql.cj.jdbc.Driver
