# 在使用Spring默认数据源Hikari的情况下配置以下配置项
spring:
   profiles:
      active: dev
   datasource:
      hikari:
         driver-class-name: com.mysql.cj.jdbc.Driver
# 自动提交从池中返回的连接
         auto-commit: true
# 连接池中维护的最小空闲连接数
         minimum-idle: 10
# 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
         maximum-pool-size: 60
# 空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
# 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
         idle-timeout: 30000
# 连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
         max-lifetime: 1800000
# 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
         connection-timeout: 30000
# 连接测试查询
         connection-test-query: select 1
         druid:
            validation-query: select 1
#connection-test-query: select 1 from dual

swagger:
   base-packages: cn.fintecher
olap:
   jwt:
# 加密秘钥
      secret: f4e2e52034348f86b67cde581c0f9eb5
# token有效时长，1小时，单位秒
      expire: 3600
      header: token
   weixin:
      APPID: wx0a0febe731c5311d
      APPSECRET: 72694063a5a58285962ad6e83e81aa45

ribbon:
   ReadTimeout: 300000
   SocketTimeout: 300000
   ConnectTimeout: 300000
hystrix:
   command:
      default: #default全局有效，service id指定应用有效
         circuitBreaker:
            sleepWindowInMilliseconds: 300000
            forceClosed: true
         execution:
            timeout:
#如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
               enabled: false
            isolation:
               thread:
                  timeoutInMilliseconds: 300000 #断路器超时时间，默认1000ms
feign:
   hystrix:
      enabled: true